# Generated by Django 5.0.6 on 2024-06-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
