# Generated by Django 5.0.6 on 2024-06-22 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='type_of_job',
        ),
        migrations.AddField(
            model_name='jobs',
            name='date_posted',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField(auto_created=True)),
                ('applied', models.BooleanField(default=False, editable=False)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.jobs')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.payment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
