# Generated by Django 5.0.6 on 2024-06-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_application_job_job_delete_jobs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Job_title',
            new_name='job_title',
        ),
    ]
